-- This file is automatically generated. Do not update by hand.

{{ '{{' }} config(schema='{{app}}_PII', alias='{{relation.alias}}') {{ '}}' }}

SELECT
{% for col in relation.columns %}
    {{ col.name|upper|indent }}
    {{- ", " if not loop.last }}
{%- endfor %}
FROM {{ '{{' }} source('{{raw_schema}}', '{{relation.name}}') {{ '}}' }}
