-- This file is automatically generated. Do not update by hand.

{{ '{{' }} config(schema='{{app}}_PII', alias='{{relation.alias}}') {{ '}}' }}

SELECT
{% for col in relation.columns %}
    {{ col.name|upper|indent }}
    {{- ", " if not loop.last }}
{%- endfor %}
FROM {{ '{{' }} source('{{raw_schema.schema_name}}', '{{relation.name}}') {{ '}}' }}
{% if raw_schema.has_soft_delete_predicate() %}
WHERE {{raw_schema.soft_delete_sql_clause()}}
{%- endif -%}
