-- This file is automatically generated. Do not update by hand.

{{ '{{' }} config(schema='{{app}}', alias='{{relation.alias}}') {{ '}}' }}

SELECT
{% for col in relation.columns -%}
  {% set app_table = app|upper ~ '.' ~ relation.name|upper %}
  {% if app_table in redactions and col.name in redactions[app_table] -%}
    {{ redactions[app_table][col.name]|safe }} as {{ col.name|upper|indent -}}
  {% else -%}
    {{ col.name|upper|indent }}
  {%- endif -%}
  {{- ", " if not loop.last }}
{%- endfor %}
FROM {{ '{{' }} source('{{raw_schema.schema_name}}', '{{relation.name}}') {{ '}}' }}
{% if raw_schema.has_soft_delete_predicate() %}
WHERE {{raw_schema.soft_delete_sql_clause()}}
{%- endif -%}
