name: dbt Schema Builder CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  run_dbt_schema_builder_tests:
    name: dbt Schema Builder Tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pip, setuptools, and wheel
      run: pip install -r requirements/pip.txt
    - name: Install dependencies
      run: pip install -r requirements/ci.txt
    - name: Install Tox
      run: pip install tox tox-gh-actions
    - name: Run Tests
      run: tox
    - name: Run Coverage
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
  run_dbt_schema_builder_code_quality:
    name: dbt Schema Builder Code Quality
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pip, setuptools, and wheel
      run: pip install -r requirements/pip.txt
    - name: Install dependencies
      run: pip install -r requirements/ci.txt
    - name: Install Tox
      run: pip install tox tox-gh-actions
    - name: Run Code Quality Checks
      run: tox -e quality
  run_dbt_schema_builder_docs:
    name: dbt Schema Builder Documentation
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pip, setuptools, and wheel
      run: pip install -r requirements/pip.txt
    - name: Install dependencies
      run: pip install -r requirements/ci.txt
    - name: Install Tox
      run: pip install tox tox-gh-actions
    - name: Run Documentation
      run: tox -e docs
