name: Upgrade Requirements

on:
  schedule:
    # will start the job at 13:15 UTC on 1st of every month
    - cron: "15 13 1 * *"
  workflow_dispatch:
    inputs:
      branch:
        description: "Target branch to create requirements PR against"
        required: true
        default: 'main'

jobs:

  call-upgrade-python-requirements-workflow:
     uses: edx/.github/.github/workflows/upgrade-python-requirements.yml@master
     with:
       branch: ${{ github.event.repository.default_branch }}
       team_reviewers: 'edx-data-engineering'
       email_address: 'data-engineering@edx.org'
       send_success_notification: true
     secrets:
       requirements_bot_github_token: ${{ secrets.REQUIREMENTS_BOT_GITHUB_TOKEN }}
       requirements_bot_github_email: ${{ secrets.REQUIREMENTS_BOT_GITHUB_EMAIL }}
       edx_smtp_username: ${{ secrets.EDX_SMTP_USERNAME }}
       edx_smtp_password: ${{ secrets.EDX_SMTP_PASSWORD }}
       